name: totalvi_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyter
  - ipykernel
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - requests
  - leidenalg
  - python-igraph
  - scikit-misc
  - pip:
      - scanpy
      - scvi-tools
      - muon